//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDto", Namespace="http://schemas.datacontract.org/2004/07/ProjectStockDTOS")]
    public partial class StockDto : object
    {
        
        private ServiceReference1.Client[] _clientsField;
        
        private string _entrepriseNameField;
        
        private System.Guid _idField;
        
        private string _nameField;
        
        private float _valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Client[] _clients
        {
            get
            {
                return this._clientsField;
            }
            set
            {
                this._clientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _entrepriseName
        {
            get
            {
                return this._entrepriseNameField;
            }
            set
            {
                this._entrepriseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float _value
        {
            get
            {
                return this._valueField;
            }
            set
            {
                this._valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ProjectStockLibrary")]
    public partial class Client : object
    {
        
        private string _emailField;
        
        private string _firstNameField;
        
        private string _lastNameField;
        
        private string _phoneField;
        
        private string _siretField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _email
        {
            get
            {
                return this._emailField;
            }
            set
            {
                this._emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _firstName
        {
            get
            {
                return this._firstNameField;
            }
            set
            {
                this._firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lastName
        {
            get
            {
                return this._lastNameField;
            }
            set
            {
                this._lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _phone
        {
            get
            {
                return this._phoneField;
            }
            set
            {
                this._phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _siret
        {
            get
            {
                return this._siretField;
            }
            set
            {
                this._siretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/ProjectStockLibrary")]
    public partial class Stock : object
    {
        
        private string _entrepriseNameField;
        
        private string _nameField;
        
        private float _valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _entrepriseName
        {
            get
            {
                return this._entrepriseNameField;
            }
            set
            {
                this._entrepriseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float _value
        {
            get
            {
                return this._valueField;
            }
            set
            {
                this._valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceStock")]
    public interface IServiceStock
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/GetStocks", ReplyAction="http://tempuri.org/IServiceStock/GetStocksResponse")]
        ServiceReference1.StockDto[] GetStocks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/GetStocks", ReplyAction="http://tempuri.org/IServiceStock/GetStocksResponse")]
        System.Threading.Tasks.Task<ServiceReference1.StockDto[]> GetStocksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/GetById", ReplyAction="http://tempuri.org/IServiceStock/GetByIdResponse")]
        ServiceReference1.StockDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/GetById", ReplyAction="http://tempuri.org/IServiceStock/GetByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.StockDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/GetAllStocks", ReplyAction="http://tempuri.org/IServiceStock/GetAllStocksResponse")]
        ServiceReference1.Stock[] GetAllStocks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/GetAllStocks", ReplyAction="http://tempuri.org/IServiceStock/GetAllStocksResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Stock[]> GetAllStocksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/update", ReplyAction="http://tempuri.org/IServiceStock/updateResponse")]
        void update(int id, ServiceReference1.StockDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/update", ReplyAction="http://tempuri.org/IServiceStock/updateResponse")]
        System.Threading.Tasks.Task updateAsync(int id, ServiceReference1.StockDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/add", ReplyAction="http://tempuri.org/IServiceStock/addResponse")]
        void add(ServiceReference1.StockDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/add", ReplyAction="http://tempuri.org/IServiceStock/addResponse")]
        System.Threading.Tasks.Task addAsync(ServiceReference1.StockDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/delete", ReplyAction="http://tempuri.org/IServiceStock/deleteResponse")]
        void delete(ServiceReference1.StockDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStock/delete", ReplyAction="http://tempuri.org/IServiceStock/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(ServiceReference1.StockDto userDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceStockChannel : ServiceReference1.IServiceStock, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceStockClient : System.ServiceModel.ClientBase<ServiceReference1.IServiceStock>, ServiceReference1.IServiceStock
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceStockClient() : 
                base(ServiceStockClient.GetDefaultBinding(), ServiceStockClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceStock.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceStockClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceStockClient.GetBindingForEndpoint(endpointConfiguration), ServiceStockClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceStockClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceStockClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceStockClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceStockClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceStockClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.StockDto[] GetStocks()
        {
            return base.Channel.GetStocks();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StockDto[]> GetStocksAsync()
        {
            return base.Channel.GetStocksAsync();
        }
        
        public ServiceReference1.StockDto GetById(int id)
        {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StockDto> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public ServiceReference1.Stock[] GetAllStocks()
        {
            return base.Channel.GetAllStocks();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Stock[]> GetAllStocksAsync()
        {
            return base.Channel.GetAllStocksAsync();
        }
        
        public void update(int id, ServiceReference1.StockDto userDto)
        {
            base.Channel.update(id, userDto);
        }
        
        public System.Threading.Tasks.Task updateAsync(int id, ServiceReference1.StockDto userDto)
        {
            return base.Channel.updateAsync(id, userDto);
        }
        
        public void add(ServiceReference1.StockDto userDto)
        {
            base.Channel.add(userDto);
        }
        
        public System.Threading.Tasks.Task addAsync(ServiceReference1.StockDto userDto)
        {
            return base.Channel.addAsync(userDto);
        }
        
        public void delete(ServiceReference1.StockDto userDto)
        {
            base.Channel.delete(userDto);
        }
        
        public System.Threading.Tasks.Task deleteAsync(ServiceReference1.StockDto userDto)
        {
            return base.Channel.deleteAsync(userDto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceStock))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceStock))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57973/ServiceStock.svc");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceStockClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceStock);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceStockClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceStock);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceStock,
        }
    }
}
