//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference4
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketDto", Namespace="http://schemas.datacontract.org/2004/07/ProjectStockDTOS")]
    public partial class MarketDto : object
    {
        
        private System.DateTime _closingDateField;
        
        private System.Guid _idField;
        
        private string _nameField;
        
        private System.DateTime _openingDateField;
        
        private ServiceReference4.Stock[] _stocksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _closingDate
        {
            get
            {
                return this._closingDateField;
            }
            set
            {
                this._closingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _openingDate
        {
            get
            {
                return this._openingDateField;
            }
            set
            {
                this._openingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference4.Stock[] _stocks
        {
            get
            {
                return this._stocksField;
            }
            set
            {
                this._stocksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/ProjectStockLibrary")]
    public partial class Stock : object
    {
        
        private string _entrepriseNameField;
        
        private string _nameField;
        
        private float _valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _entrepriseName
        {
            get
            {
                return this._entrepriseNameField;
            }
            set
            {
                this._entrepriseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float _value
        {
            get
            {
                return this._valueField;
            }
            set
            {
                this._valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IServiceMarche")]
    public interface IServiceMarche
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/GetMarkets", ReplyAction="http://tempuri.org/IServiceMarche/GetMarketsResponse")]
        ServiceReference4.MarketDto[] GetMarkets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/GetMarkets", ReplyAction="http://tempuri.org/IServiceMarche/GetMarketsResponse")]
        System.Threading.Tasks.Task<ServiceReference4.MarketDto[]> GetMarketsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/GetById", ReplyAction="http://tempuri.org/IServiceMarche/GetByIdResponse")]
        ServiceReference4.MarketDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/GetById", ReplyAction="http://tempuri.org/IServiceMarche/GetByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference4.MarketDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/Update", ReplyAction="http://tempuri.org/IServiceMarche/UpdateResponse")]
        void Update(int id, ServiceReference4.MarketDto marketDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/Update", ReplyAction="http://tempuri.org/IServiceMarche/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(int id, ServiceReference4.MarketDto marketDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/Add", ReplyAction="http://tempuri.org/IServiceMarche/AddResponse")]
        void Add(ServiceReference4.MarketDto marketDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/Add", ReplyAction="http://tempuri.org/IServiceMarche/AddResponse")]
        System.Threading.Tasks.Task AddAsync(ServiceReference4.MarketDto marketDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/Delete", ReplyAction="http://tempuri.org/IServiceMarche/DeleteResponse")]
        void Delete(ServiceReference4.MarketDto marketDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMarche/Delete", ReplyAction="http://tempuri.org/IServiceMarche/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(ServiceReference4.MarketDto marketDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceMarcheChannel : ServiceReference4.IServiceMarche, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceMarcheClient : System.ServiceModel.ClientBase<ServiceReference4.IServiceMarche>, ServiceReference4.IServiceMarche
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceMarcheClient() : 
                base(ServiceMarcheClient.GetDefaultBinding(), ServiceMarcheClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceMarche.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceMarcheClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceMarcheClient.GetBindingForEndpoint(endpointConfiguration), ServiceMarcheClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceMarcheClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceMarcheClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceMarcheClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceMarcheClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceMarcheClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference4.MarketDto[] GetMarkets()
        {
            return base.Channel.GetMarkets();
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.MarketDto[]> GetMarketsAsync()
        {
            return base.Channel.GetMarketsAsync();
        }
        
        public ServiceReference4.MarketDto GetById(int id)
        {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.MarketDto> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public void Update(int id, ServiceReference4.MarketDto marketDto)
        {
            base.Channel.Update(id, marketDto);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(int id, ServiceReference4.MarketDto marketDto)
        {
            return base.Channel.UpdateAsync(id, marketDto);
        }
        
        public void Add(ServiceReference4.MarketDto marketDto)
        {
            base.Channel.Add(marketDto);
        }
        
        public System.Threading.Tasks.Task AddAsync(ServiceReference4.MarketDto marketDto)
        {
            return base.Channel.AddAsync(marketDto);
        }
        
        public void Delete(ServiceReference4.MarketDto marketDto)
        {
            base.Channel.Delete(marketDto);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(ServiceReference4.MarketDto marketDto)
        {
            return base.Channel.DeleteAsync(marketDto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceMarche))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceMarche))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57973/ServiceMarche.svc");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceMarcheClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceMarche);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceMarcheClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceMarche);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceMarche,
        }
    }
}
